"""Generates docs/CONFIG.md from the pydantic schema, so documentation cannot drift from code."""

from __future__ import annotations

import types
import typing
from collections.abc import Iterator

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from vigil.config.settings import Settings

_CONSTRAINTS = ("gt", "ge", "lt", "le", "min_length", "max_length")


def _submodel(annotation: object) -> tuple[type[BaseModel], bool] | None:
    """The nested model of a field, and whether it is a sequence of them."""
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation, False
    origin = typing.get_origin(annotation)
    if origin is tuple or origin is list:
        for arg in typing.get_args(annotation):
            if isinstance(arg, type) and issubclass(arg, BaseModel):
                return arg, True
    return None


def _type_name(annotation: object) -> str:
    if isinstance(annotation, types.UnionType) or typing.get_origin(annotation) is typing.Union:
        return " | ".join(_type_name(a) for a in typing.get_args(annotation))
    if typing.get_origin(annotation) is typing.Literal:
        return "one of " + ", ".join(repr(a) for a in typing.get_args(annotation))
    if isinstance(annotation, type):
        return annotation.__name__
    return str(annotation).replace("typing.", "")


def _constraints(field: FieldInfo) -> str:
    found = []
    for meta in field.metadata:
        for name in _CONSTRAINTS:
            if (value := getattr(meta, name, None)) is not None:
                found.append(f"{name}={value}")
    return ", ".join(found)


def _rows(model: type[BaseModel], prefix: str) -> Iterator[tuple[str, str, str, str]]:
    for name, field in model.model_fields.items():
        path = f"{prefix}{name}"
        sub = _submodel(field.annotation)
        if sub is not None:
            model_type, is_seq = sub
            yield from _rows(model_type, f"{path}[]." if is_seq else f"{path}.")
            continue
        default = field.get_default(call_default_factory=True)
        yield path, _type_name(field.annotation), repr(default), _constraints(field)


def render_config_reference() -> str:
    lines = [
        "# Configuration reference",
        "",
        "Generated by `vigil doctor --dump-config`. Do not edit by hand.",
        "",
        "Layers, last wins: code defaults, `config/vigil.yaml`, `config/vigil.local.yaml`,",
        "`VIGIL_<SECTION>__<KEY>` environment variables (and `.env`), then CLI overrides.",
        "Unknown keys are errors. Strings may use `${env:NAME}`, `${env:NAME:-default}` or",
        "`${other.key}`.",
        "",
    ]
    section = ""
    for path, type_name, default, constraints in _rows(Settings, ""):
        top = path.split(".")[0].split("[")[0]
        if top != section:
            section = top
            lines += [
                "",
                f"## `{section}`",
                "",
                "| key | type | default | constraints |",
                "|-----|------|---------|-------------|",
            ]
        lines.append(f"| `{path}` | {type_name} | `{default}` | {constraints} |")
    lines.append("")
    return "\n".join(lines)
